services:
  hydrodb:
    image: influxdb:1.8.10
    restart: unless-stopped
    env_file:
      - ./src/.env
    volumes:
      - ./resources/init.iql:/docker-entrypoint-initdb.d/init.iql:ro
      - hydrodata:/var/lib/influxdb
    ports:
      - 8086:8086
    environment:
      - ${INFLUXDB_DB:-database} 
      - ${INFLUXDB_ADMIN_USER:-admin}
      - ${INFLUXDB_ADMIN_PASSWORD:-adminpassword}
      - ${INFLUXDB_USER:-databaseuser}
      - ${INFLUXDB_USER_PASSWORD:-userpassword}
      
  hydrobot:
    image: hydrobot:0.1.0
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./src/.env
    depends_on:
      - hydrodb
    links:
      - hydrodb
    volumes:
      - hydrodata:/hydrostatus
    environment:
      - ${INFLUXDB_DB:-database}
      - ${INFLUXDB_RP:-autogen}
      - ${INFLUXDB_USER:-user}
      - ${INFLUXDB_USER_PASSWORD:-password}
      - ${INFLUXDB_SERVER:-https://127.0.0.1:8086}
      - ${TOKEN:-token}

volumes:
  hydrodata: