{
 "title": "water monitor",
 "time": { "from": "now/M", "to": "now/M" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Current Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "flowlpm" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "water",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "flow" }
     ]
    }
   ]
  },
  {
   "title": "Hourly Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "alias": "Minute",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "water",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "flow" }
     ]
    }
   ]
  },
  {
   "title": "Weekly Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "alias": "Hourly",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "water",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "flow" }
     ]
    }
   ]
  },
  {
   "title": "Hourly Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "water",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "flow" }
     ]
    }
   ]
  },
  {
   "title": "Daily Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "water",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "flow" }
     ]
    }
   ]
  },
  {
   "title": "Usage: 12 Hours",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "alias": "Hourly",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "water",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "flow" }
     ]
    }
   ]
  },
  {
   "title": "Monthly Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "alias": "Daily",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "minute",
     "select": [
      [
       { "params": [ "1m-usage" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Monthly Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "minute",
     "select": [
      [
       { "params": [ "1m-usage" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Yearly Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "hour",
     "select": [
      [
       { "params": [ "1h-usage" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Usage Trend",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 18, "x": 5, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "litreh" } },
   "targets": [
    {
     "alias": "Hourly",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "water",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "flow" }
     ]
    }
   ]
  },
  {
   "title": "Monthly Cost Est.",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "minute",
     "select": [
      [
       { "params": [ "1m-usage" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/ 1000 * 43.35" ], "type": "math" }
      ]
     ]
    }
   ]
  }
 ]
}